// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwsPGO0ZkNe_EsgwhOg7V7Yu4csje6xzE',
    appId: '1:188035146333:web:352d43d66b984dd43723b4',
    messagingSenderId: '188035146333',
    projectId: 'recycling-bonus',
    authDomain: 'recycling-bonus.firebaseapp.com',
    storageBucket: 'recycling-bonus.appspot.com',
    measurementId: 'G-DC08Y2L0KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtKS4CeLLJccdz1FLuoRGo05FnBXFrHGs',
    appId: '1:188035146333:android:6ab73070593e55c73723b4',
    messagingSenderId: '188035146333',
    projectId: 'recycling-bonus',
    storageBucket: 'recycling-bonus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM_MCPdvZmEcZnI5MhLo0GfkNsdls9B0k',
    appId: '1:188035146333:ios:5d96938909c24fcc3723b4',
    messagingSenderId: '188035146333',
    projectId: 'recycling-bonus',
    storageBucket: 'recycling-bonus.appspot.com',
    iosClientId: '188035146333-nv8ejae1vi8cc7j6o5ns0du1kupeps09.apps.googleusercontent.com',
    iosBundleId: 'com.example.butterflyTouch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM_MCPdvZmEcZnI5MhLo0GfkNsdls9B0k',
    appId: '1:188035146333:ios:5d96938909c24fcc3723b4',
    messagingSenderId: '188035146333',
    projectId: 'recycling-bonus',
    storageBucket: 'recycling-bonus.appspot.com',
    iosClientId: '188035146333-nv8ejae1vi8cc7j6o5ns0du1kupeps09.apps.googleusercontent.com',
    iosBundleId: 'com.example.butterflyTouch',
  );
}
